target 'KMM sample' do
  use_frameworks!
  source 'https://github.com/soramitsu/common-mobile-libraries.git'
  platform :ios, '14.1'
  #pod 'X-Networking', '~>0.0.19'
  #pod 'commonNetworking', :path => '../commonNetworking'
  pod 'X-Networking', :podspec => 'https://raw.githubusercontent.com/soramitsu/x-networking/master/X-Networking/0.0.19/X-Networking.podspec'
end
